### ISSUE TITLE
documentation is pathetic

### ISSUE THREAD

**Issue by tippi-fifestarr** [cromewar/1w33k-smartContracts#2]
I don't know what "use brownie to deploy" means.

other than looking at the code, how does this interact with our project?
what does it do?
what is it for?

**Comment by cromewar** [comment]
Peter wanted an alternative to Poap, so this project is an example about how to use the NTT and mint the badges.

**Comment by tippi-fifestarr** [comment]
what is your hope for each of us **todo** after seeing this repo:
peter will see this and ____________
leo will see this and ____________
tippi will see this and _______________
shucks will see this and ________________
cromewar will see this and __________________

**Comment by cromewar** [comment]
I don't think I have any pretentions, this project is just s showcase about how to implement the same solution using another standard.

 I'll expect you to see this just as a reference of an alternative, that's all.

**Comment by tippi-fifestarr** [comment]
nice
